apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-go
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-go
  targetCPUUtilizationPercentage: 25
